
import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const db=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const st={user:null,year:null,classes:[],sports:[],sportCounts:{},lessons:[],modules:[],tests:[],exceptions:[],hof:[],month:new Date(),currentSport:null,currentExercises:[],categories:[]};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const iconMap={'pallacanestro':'🏀','ultimate-frisbee':'🥏','pallamano':'🤾','pallavolo':'🏐','badminton':'🏸','tennis':'🎾','calcio-a-5':'⚽','atletica-leggera':'🏃','rugby':'🏉','orienteering':'🧭','giochi-tradizionali':'🪁','baseball':'⚾','judo':'🥋','giocoleria':'🎪','fitness':'🏋️'};
const phaseLabel={activation:'ATTIVAZIONE',main:'PARTE CENTRALE',final:'APPLICAZIONE FINALE',closing:'CHIUSURA',warmup:'ATTIVAZIONE',technical:'TECNICA',tactical:'PARTE CENTRALE',game:'PARTITA / SSG',assessment:'VALUTAZIONE',cooldown:'CHIUSURA'};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2300)}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));let m={dashboard:['PANORAMICA','Dashboard'],calendar:['ANNO SCOLASTICO','Calendario'],classes:['GESTIONE','Classi'],planner:['MOTORE DIDATTICO','Programmazione'],sports:['MEGA ARCHIVIO','Archivio sport'],tests:['VALUTAZIONE','Test motori'],settings:['CONFIGURAZIONE','Impostazioni']}[v];$('#pageKicker').textContent=m[0];$('#pageTitle').textContent=m[1];if(v==='sports')renderSports();if(v==='tests')renderTests();if(v==='calendar')renderCalendar();if(v==='settings')renderSettings()}
$$('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>go(b.dataset.jump));$('#quickPlan').onclick=()=>go('planner');$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());

async function loadCore(){
  let [y,c,s,l,m,t,e,h]=await Promise.all([
    db.from('pe_school_years').select('*').eq('is_active',true).maybeSingle(),
    db.from('pe_classes').select('*').eq('archived',false).order('grade'),
    db.from('pe_sports').select('*').eq('active',true).order('name'),
    db.from('pe_lessons').select('*,pe_classes(name),pe_sports(name)').order('lesson_date').limit(200),
    db.from('pe_sport_modules').select('*,pe_classes(name),pe_sports(name)').order('start_date',{ascending:false}).limit(100),
    db.from('pe_motor_tests').select('*').eq('active',true).order('name'),
    db.from('pe_calendar_exceptions').select('*').order('exception_date'),
    db.from('pe_motor_test_hall_of_fame').select('*').limit(40)
  ]);
  st.year=y.data;st.classes=c.data||[];st.sports=s.data||[];st.lessons=l.data||[];st.modules=m.data||[];st.tests=t.data||[];st.exceptions=e.data||[];st.hof=h.data||[];
  const counts=await Promise.all(st.sports.map(async sp=>{let{count}=await db.from('pe_exercises').select('*',{count:'exact',head:true}).eq('sport_id',sp.id).eq('active',true).eq('audit_status','VERIFIED');return[sp.id,count||0]}));
  st.sportCounts=Object.fromEntries(counts);populateSelects();renderDashboard();renderClasses();renderModules();renderTests();renderSettings();
}
function populateSelects(){
  const co='<option value="">Seleziona classe</option>'+st.classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${c.student_count} alunni</option>`).join('');
  ['planClass','sessionClass','rankingClass','exceptionClass'].forEach(id=>$( '#'+id).innerHTML=co);
  const so='<option value="">Seleziona sport</option>'+st.sports.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
  $('#planSport').innerHTML=so;
  const to='<option value="">Seleziona test</option>'+st.tests.map(t=>`<option value="${t.id}">${esc(t.name)} (${esc(t.unit)})</option>`).join('');
  $('#sessionTest').innerHTML=to;$('#hofTest').innerHTML='<option value="">Tutti i test</option>'+st.tests.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');
  if(!$('#planStart').value)$('#planStart').value=new Date().toISOString().slice(0,10);
  if(!$('#sessionDate').value)$('#sessionDate').value=new Date().toISOString().slice(0,10);
}
function listItem(a,b,c=''){return`<div class="list-item"><div><strong>${esc(a)}</strong><small>${esc(b)}</small></div>${c}</div>`}
function renderDashboard(){
  $('#statClasses').textContent=st.classes.length;$('#statSports').textContent=st.sports.length;$('#statLessons').textContent=st.lessons.length;$('#statTests').textContent=st.tests.length;
  $('#heroExerciseCount').textContent=Object.values(st.sportCounts).reduce((a,b)=>a+b,0)||1390;
  const today=new Date().toISOString().slice(0,10),u=st.lessons.filter(x=>x.lesson_date>=today).slice(0,6);
  $('#upcomingLessons').innerHTML=u.map(x=>`<div class="list-item" data-lesson="${x.id}"><div><strong>${esc(x.title)}</strong><small>${esc(x.pe_classes?.name||'')} · ${fmt(x.lesson_date)}</small></div><span class="chip good">${x.duration_min}'</span></div>`).join('')||listItem('Nessuna lezione futura','Programma il primo modulo');
  $$('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));
  $('#dashboardHof').innerHTML=st.hof.slice(0,6).map(x=>listItem(`${x.first_name} ${x.last_name}`,`${x.test_name} · ${x.school_year_label}`,`<span class="chip gold">${x.result_value} ${esc(x.unit)}</span>`)).join('')||listItem('Nessun record ancora','Inserisci i primi risultati');
}
function renderClasses(){
  $('#classesGrid').innerHTML=st.classes.map(c=>`<article class="class-card" data-class="${c.id}"><span class="kicker">CLASSE</span><h4>${esc(c.name)}</h4><div class="class-counts"><span class="chip">${c.student_count} alunni</span><span class="chip">♀ ${c.female_count??'—'}</span><span class="chip">♂ ${c.male_count??'—'}</span></div><div class="edit-hint">Apri e modifica →</div></article>`).join('')||`<article class="class-card"><h4>Nessuna classe</h4><p>Creane una per iniziare.</p></article>`;
  $$('[data-class]').forEach(x=>x.onclick=()=>openClass(x.dataset.class));
}
$('#newClassBtn').onclick=()=>openClass(null);
async function openClass(id){
  $('#classId').value=id||'';$('#studentRows').innerHTML='';$('#classMsg').textContent='';
  if(id){
    const c=st.classes.find(x=>x.id===id);$('#classModalTitle').textContent=c.name;$('#className').value=c.name;$('#classGrade').value=c.grade;$('#femaleCount').value=c.female_count??0;$('#maleCount').value=c.male_count??0;
    const{data:en}=await db.from('pe_student_enrollments').select('*,pe_students(*)').eq('class_id',id).eq('active',true);
    (en||[]).forEach(x=>addStudentRow(x.pe_students?.first_name,x.pe_students?.last_name,x.pe_students?.sex,x.pe_students?.id));
  }else{$('#classModalTitle').textContent='Nuova classe';$('#className').value='';$('#classGrade').value=1;$('#femaleCount').value=0;$('#maleCount').value=0}
  await renderLevelGrid(id);$('#classModal').showModal();
}
function addStudentRow(first='',last='',sex='F',id=''){let d=document.createElement('div');d.className='student-row';d.dataset.studentId=id;d.innerHTML=`<input class="s-first" placeholder="Nome" value="${esc(first)}"><input class="s-last" placeholder="Cognome" value="${esc(last)}"><select class="s-sex"><option value="F" ${sex==='F'?'selected':''}>F</option><option value="M" ${sex==='M'?'selected':''}>M</option></select><button type="button">×</button>`;d.querySelector('button').onclick=()=>d.remove();$('#studentRows').appendChild(d)}
$('#addStudentRow').onclick=()=>addStudentRow();
async function renderLevelGrid(classId){
  let levels={};if(classId){let{data}=await db.from('pe_class_sport_levels').select('*').eq('class_id',classId);(data||[]).forEach(x=>levels[x.sport_id]=x.level)}
  $('#sportLevelGrid').innerHTML=st.sports.map(s=>`<div class="level-item"><span>${iconMap[s.slug]||'●'} ${esc(s.name)}</span><select data-sport-level="${s.id}"><option value="">Non impostato</option>${[1,2,3,4,5].map(n=>`<option value="${n}" ${levels[s.id]==n?'selected':''}>${n} · ${['','Principiante','Base','Intermedio','Avanzato','Molto avanzato'][n]}</option>`).join('')}</select></div>`).join('');
}
$('#classForm').onsubmit=async e=>{
  e.preventDefault();const id=$('#classId').value||null,f=+$('#femaleCount').value,m=+$('#maleCount').value,total=f+m;$('#classMsg').textContent='Salvataggio…';
  let cid=id;
  if(id){let{error}=await db.from('pe_classes').update({name:$('#className').value,grade:+$('#classGrade').value,female_count:f,male_count:m,student_count:total}).eq('id',id);if(error)return $('#classMsg').textContent=error.message}
  else{let{data,error}=await db.from('pe_classes').insert({owner_id:st.user.id,school_year_id:st.year.id,name:$('#className').value,grade:+$('#classGrade').value,female_count:f,male_count:m,student_count:total}).select().single();if(error)return $('#classMsg').textContent=error.message;cid=data.id}
  for(const row of $$('.student-row')){let sid=row.dataset.studentId,first=row.querySelector('.s-first').value.trim(),last=row.querySelector('.s-last').value.trim(),sex=row.querySelector('.s-sex').value;if(!first||!last)continue;if(sid){await db.from('pe_students').update({first_name:first,last_name:last,sex}).eq('id',sid)}else{let{data}=await db.from('pe_students').insert({owner_id:st.user.id,first_name:first,last_name:last,sex}).select().single();if(data){sid=data.id;await db.from('pe_student_enrollments').insert({owner_id:st.user.id,student_id:sid,class_id:cid,school_year_id:st.year.id,active:true})}}}
  for(const sel of $$('[data-sport-level]'))if(sel.value)await db.from('pe_class_sport_levels').upsert({owner_id:st.user.id,class_id:cid,sport_id:sel.dataset.sportLevel,level:+sel.value},{onConflict:'owner_id,class_id,sport_id'});
  $('#classModal').close();toast('Classe salvata');await loadCore();
}
function renderModules(){$('#moduleList').innerHTML=st.modules.slice(0,18).map(x=>listItem(x.title,`${x.pe_classes?.name||''} · ${x.planned_weeks} settimane`, `<span class="chip">${x.status}</span>`)).join('')||listItem('Nessun modulo','Creane uno dal generatore')}
$('#plannerForm').onsubmit=async e=>{e.preventDefault();const cid=$('#planClass').value,sid=$('#planSport').value;if(!cid||!sid)return;const sp=st.sports.find(x=>x.id===sid),cl=st.classes.find(x=>x.id===cid);$('#plannerMsg').textContent='Genero la progressione…';let{data:m,error}=await db.from('pe_sport_modules').insert({owner_id:st.user.id,class_id:cid,sport_id:sid,module_type:'automatic',title:`${sp.name} · ${cl.name}`,start_date:$('#planStart').value,planned_weeks:+$('#planWeeks').value,lesson_duration_min:+$('#planMinutes').value,level_override:$('#planLevel').value?+$('#planLevel').value:null,progression_mode:'progressive',status:'planned'}).select().single();if(error)return $('#plannerMsg').textContent=error.message;let{error:er}=await db.rpc('pe_generate_module_plan',{p_module_id:m.id,p_regenerate:false});if(er)return $('#plannerMsg').textContent=er.message;$('#plannerMsg').textContent='Programmazione generata.';toast('Modulo generato');await loadCore()}
async function openLesson(id){let{data:l}=await db.from('pe_lessons').select('*,pe_classes(name),pe_sports(name)').eq('id',id).single(),{data:it}=await db.from('pe_lesson_exercises').select('*,pe_exercises(*)').eq('lesson_id',id).order('order_no');$('#lessonModalTitle').textContent=l.title;$('#lessonBody').innerHTML=`<div class="category-pills"><span class="chip">${esc(l.pe_classes?.name)}</span><span class="chip">${fmt(l.lesson_date)}</span><span class="chip">${l.duration_min}'</span></div><div class="lesson-timeline">${(it||[]).map(x=>`<div class="lesson-row"><div class="lesson-time">${x.duration_min}'</div><div><span class="kicker">${phaseLabel[x.phase]||x.phase}</span><strong>${esc(x.custom_title||x.pe_exercises?.name||'Attività')}</strong><p>${esc(x.custom_explanation||x.pe_exercises?.student_explanation||'')}</p>${x.station_count?`<div class="category-pills"><span class="chip">${x.station_count} campi/stazioni</span><span class="chip">${x.players_per_group} alunni/gruppo</span></div>`:''}</div>${x.exercise_id?`<button class="btn secondary small-btn" data-open-ex="${x.exercise_id}">Dettagli</button>`:''}</div>`).join('')}</div>`;$$('[data-open-ex]').forEach(b=>b.onclick=()=>openExercise(b.dataset.openEx));$('#lessonModal').showModal()}
function renderSports(){const term=$('#sportSearch').value.toLowerCase().trim();const arr=st.sports.filter(x=>!term||x.name.toLowerCase().includes(term));$('#archiveTotal').textContent=Object.values(st.sportCounts).reduce((a,b)=>a+b,0);$('#sportsGrid').innerHTML=arr.map((s,i)=>`<article class="sport-card tone-${(i%5)+1}" data-sport="${s.id}"><div class="sport-icon">${iconMap[s.slug]||'🏅'}</div><h4>${esc(s.name)}</h4><p>${esc(s.description||'Archivio didattico con progressioni, varianti e spiegazioni complete.')}</p><div class="sport-footer"><span class="sport-count">${st.sportCounts[s.id]||0} attività</span><span class="sport-arrow">→</span></div></article>`).join('');$$('[data-sport]').forEach(x=>x.onclick=()=>openSport(x.dataset.sport))}
$('#sportSearch').oninput=renderSports;
$('#backSports').onclick=()=>{$('#sportDetail').classList.add('hidden');$('#sportLanding').classList.remove('hidden');st.currentSport=null};
async function openSport(id){st.currentSport=st.sports.find(x=>x.id===id);$('#sportLanding').classList.add('hidden');$('#sportDetail').classList.remove('hidden');let{data:cats}=await db.from('pe_categories').select('*').eq('sport_id',id).order('sort_order');st.categories=cats||[];$('#categoryFilter').innerHTML='<option value="">Tutte le categorie</option>'+st.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#sportDetailHero').innerHTML=`<span class="kicker">${iconMap[st.currentSport.slug]||'🏅'} ARCHIVIO SPORT</span><h3>${esc(st.currentSport.name)}</h3><p>${st.sportCounts[id]||0} attività verificate · ${st.categories.length} categorie</p><div class="category-pills">${st.categories.slice(0,12).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div>`;await loadExercises()}
async function loadExercises(){let q=db.from('pe_exercises').select('id,name,student_explanation,difficulty,duration_min,duration_max,field_dimensions,category_id,fun_score').eq('sport_id',st.currentSport.id).eq('active',true).eq('audit_status','VERIFIED').order('name').limit(500);if($('#categoryFilter').value)q=q.eq('category_id',$('#categoryFilter').value);if($('#difficultyFilter').value)q=q.eq('difficulty',+$('#difficultyFilter').value);if($('#exerciseSearch').value.trim())q=q.ilike('name',`%${$('#exerciseSearch').value.trim()}%`);let{data}=await q;st.currentExercises=data||[];$('#exerciseGrid').innerHTML=st.currentExercises.map(e=>`<article class="exercise-card"><h4>${esc(e.name)}</h4><p>${esc((e.student_explanation||'').slice(0,160))}${(e.student_explanation||'').length>160?'…':''}</p><div class="category-pills"><span class="chip">Liv. ${e.difficulty||'—'}</span><span class="chip">${e.duration_min||'—'}–${e.duration_max||'—'}'</span>${e.fun_score?`<span class="chip good">Fun ${e.fun_score}/5</span>`:''}</div><button class="btn secondary small-btn open-ex" data-open-ex="${e.id}">Apri scheda</button></article>`).join('');$$('[data-open-ex]').forEach(b=>b.onclick=()=>openExercise(b.dataset.openEx))}
['categoryFilter','difficultyFilter'].forEach(id=>$('#'+id).onchange=loadExercises);$('#exerciseSearch').oninput=loadExercises;
async function openExercise(id){let{data:e}=await db.from('pe_exercises').select('*,pe_categories(name)').eq('id',id).single();$('#exerciseModalTitle').textContent=e.name;const box=(t,v)=>`<div class="detail-box"><b>${t}</b><p>${esc(v||'—')}</p></div>`;$('#exerciseModalBody').innerHTML=`<div class="category-pills"><span class="chip">${esc(e.pe_categories?.name||'')}</span><span class="chip">Livello ${e.difficulty||'—'}</span><span class="chip">${e.duration_min||'—'}–${e.duration_max||'—'}'</span><span class="chip">${esc(e.field_dimensions||'')}</span></div><div class="detail-grid" style="margin-top:12px">${box('COSA DEVI FARE',e.student_explanation)}${box('SPIEGAZIONE DOCENTE',e.teacher_explanation)}${box('OBIETTIVO',e.objective)}${box('ORGANIZZAZIONE',e.organization)}${box('REGOLE',e.rules)}${box('VARIANTI',e.variants)}${box('FACILITAZIONI',e.regressions)}${box('PROGRESSIONI',e.progressions)}${box('ERRORI',e.common_errors)}${box('CORREZIONI',e.corrections)}${box('CUE DOCENTE',e.teacher_cues)}${box('SICUREZZA',e.safety_notes)}</div>`;$('#exerciseModal').showModal()}
function renderTests(){$('#testsGrid').innerHTML=st.tests.map(t=>`<article class="test-card"><h4>${esc(t.name)}</h4><p>Unità: ${esc(t.unit)}</p><div class="test-direction">${t.result_direction==='lower_better'?'↓ MIGLIORE IL VALORE PIÙ BASSO':'↑ MIGLIORE IL VALORE PIÙ ALTO'}</div></article>`).join('');loadHof()}
$('#newTestBtn').onclick=()=>$('#testModal').showModal();
$('#testForm').onsubmit=async e=>{e.preventDefault();const slug=$('#testName').value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now();let{error}=await db.from('pe_motor_tests').insert({owner_id:st.user.id,name:$('#testName').value,slug,unit:$('#testUnit').value,result_direction:$('#testDirection').value,is_default:false,active:true});if(error)return toast(error.message);$('#testModal').close();toast('Test creato');await loadCore()}
$$('[data-testtab]').forEach(b=>b.onclick=()=>{$$('[data-testtab]').forEach(x=>x.classList.toggle('active',x===b));$$('.testtab').forEach(x=>x.classList.toggle('active',x.id===`testtab-${b.dataset.testtab}`));if(b.dataset.testtab==='rankings')loadRankings();if(b.dataset.testtab==='hof')loadHof()});
$('#sessionForm').onsubmit=async e=>{e.preventDefault();const cid=$('#sessionClass').value,tid=$('#sessionTest').value,date=$('#sessionDate').value;if(!cid||!tid)return;let test=st.tests.find(x=>x.id===tid);let{data:ses,error}=await db.from('pe_motor_test_sessions').insert({owner_id:st.user.id,school_year_id:st.year.id,class_id:cid,test_id:tid,session_date:date,title:test.name}).select().single();if(error)return toast(error.message);renderResultEntry(ses,test,cid)}
async function renderResultEntry(session,test,cid){let{data:en}=await db.from('pe_student_enrollments').select('student_id,pe_students(*)').eq('class_id',cid).eq('active',true);$('#sessionResultsArea').innerHTML=`<div class="panel glass" style="margin-top:14px"><span class="kicker">${esc(test.name)}</span><h3>Inserisci risultati</h3><div id="resultRows">${(en||[]).map(x=>`<div class="ranking-row"><div>${x.pe_students.sex==='F'?'♀':'♂'}</div><div><strong>${esc(x.pe_students.first_name)} ${esc(x.pe_students.last_name)}</strong></div><input style="max-width:120px" type="number" step="0.01" data-result-student="${x.student_id}" placeholder="${esc(test.unit)}"></div>`).join('')}</div><button id="saveResults" class="btn primary" style="margin-top:12px">Salva risultati</button></div>`;$('#saveResults').onclick=async()=>{const rows=[];$$('[data-result-student]').forEach(i=>{if(i.value!=='')rows.push({owner_id:st.user.id,session_id:session.id,student_id:i.dataset.resultStudent,result_value:+i.value})});if(rows.length){let{error}=await db.from('pe_motor_test_results').insert(rows);if(error)return toast(error.message)}toast('Risultati salvati');await loadCore();loadRankings()}}
async function loadRankings(){const cid=$('#rankingClass').value||st.classes[0]?.id,sex=$('#rankingSex').value;if(!cid)return;let{data:t}=await db.from('pe_motor_test_total_rankings').select('*').eq('class_id',cid).eq('sex',sex).order('total_place');$('#totalRanking').innerHTML=(t||[]).map(x=>`<div class="ranking-row"><div class="rank-pos">${x.total_place}</div><div><strong>${esc(x.first_name)} ${esc(x.last_name)}</strong><small>${x.scored_results} risultati a punti</small></div><div class="rank-points">${x.total_points} pt</div></div>`).join('')||'<p class="muted">Nessun risultato.</p>';let{data:sess}=await db.from('pe_motor_test_sessions').select('id').eq('class_id',cid).order('session_date',{ascending:false}).limit(1);if(sess?.length){let{data:r}=await db.from('pe_motor_test_rankings').select('*').eq('session_id',sess[0].id).eq('sex',sex).order('place');$('#singleRanking').innerHTML=(r||[]).map(x=>`<div class="ranking-row"><div class="rank-pos">${x.place}</div><div><strong>${esc(x.first_name)} ${esc(x.last_name)}</strong><small>${x.result_value} ${esc(x.unit)}</small></div><div class="rank-points">${x.points} pt</div></div>`).join('')}else $('#singleRanking').innerHTML='<p class="muted">Nessun test registrato.</p>'}
$('#rankingClass').onchange=loadRankings;$('#rankingSex').onchange=loadRankings;
async function loadHof(){let q=db.from('pe_motor_test_hall_of_fame').select('*');if($('#hofTest').value)q=q.eq('test_id',$('#hofTest').value);if($('#hofSex').value)q=q.eq('sex',$('#hofSex').value);let{data}=await q.limit(100);$('#hofGrid').innerHTML=(data||[]).map(x=>`<article class="hof-card"><div class="medal">🏆</div><span class="kicker">${esc(x.test_name)} · ${x.sex==='F'?'FEMMINE':'MASCHI'}</span><h4>${esc(x.first_name)} ${esc(x.last_name)}</h4><div class="hof-value">${x.result_value} ${esc(x.unit)}</div><small>${esc(x.class_name||'')} · ${esc(x.school_year_label||'')}</small></article>`).join('')||'<p class="muted">La Hall of Fame si riempirà con i primi risultati.</p>'}
$('#hofTest').onchange=loadHof;$('#hofSex').onchange=loadHof;
function renderCalendar(){let d=st.month,y=d.getFullYear(),m=d.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(d);let first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7)),html=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=>`<div class="cal-head">${x}</div>`).join('');for(let i=0;i<42;i++){let day=new Date(start);day.setDate(start.getDate()+i);let iso=day.toISOString().slice(0,10),ev=st.lessons.filter(x=>x.lesson_date===iso).map(x=>`<div class="cal-event" data-lesson="${x.id}">${esc(x.title)}</div>`).join(''),ex=st.exceptions.filter(x=>iso>=x.exception_date&&iso<=(x.end_date||x.exception_date)).map(x=>`<div class="cal-event exception">${esc(x.reason||x.exception_type)}</div>`).join('');html+=`<div class="cal-day ${day.getMonth()!==m?'off':''}"><div class="cal-num">${day.getDate()}</div>${ex}${ev}</div>`}$('#calendarGrid').innerHTML=html;$$('#calendarGrid [data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson))}
$('#prevMonth').onclick=()=>{st.month=new Date(st.month.getFullYear(),st.month.getMonth()-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{st.month=new Date(st.month.getFullYear(),st.month.getMonth()+1,1);renderCalendar()};
function openException(scope='school'){$('#exceptionScope').value=scope;$('#exceptionClassWrap').classList.toggle('hidden',scope==='school');$('#exceptionModal').showModal()}$('#addException').onclick=()=>openException();$('#schoolClosureBtn').onclick=()=>openException();$('#exceptionScope').onchange=()=>$('#exceptionClassWrap').classList.toggle('hidden',$('#exceptionScope').value==='school');
$('#exceptionForm').onsubmit=async e=>{e.preventDefault();const school=$('#exceptionScope').value==='school';let{error}=await db.from('pe_calendar_exceptions').insert({owner_id:st.user.id,school_year_id:st.year.id,class_id:school?null:$('#exceptionClass').value,exception_date:$('#exceptionStart').value,end_date:$('#exceptionEnd').value,scope:school?'school':'class',exception_type:$('#exceptionType').value,reason:$('#exceptionReason').value||null,all_day:true});if(error)return toast(error.message);$('#exceptionModal').close();toast('Calendario aggiornato');await loadCore();renderCalendar()}
function renderSettings(){$('#closureList').innerHTML=st.exceptions.filter(x=>x.scope==='school').map(x=>listItem(x.reason||'Chiusura',`${fmt(x.exception_date)}${x.end_date!==x.exception_date?' → '+fmt(x.end_date):''}`,`<span class="chip">${x.exception_type}</span>`)).join('')||listItem('Nessuna chiusura','Inserisci ponti e vacanze')}
$('#migrateYearBtn').onclick=()=>$('#migrateModal').showModal();$('#migrateForm').onsubmit=async e=>{e.preventDefault();let{error}=await db.rpc('pe_migrate_school_year',{p_new_label:$('#newYearLabel').value,p_start_date:$('#newYearStart').value,p_end_date:$('#newYearEnd').value,p_archive_old:true});if(error)return toast(error.message);$('#migrateModal').close();toast('Nuovo anno scolastico creato');await loadCore()}
function setSyncState(kind='ok',label='Sincronizzato'){const el=$('#syncStatus');if(!el)return;el.classList.toggle('syncing',kind==='syncing');el.classList.toggle('error',kind==='error');const t=el.querySelector('span');if(t)t.textContent=label}
let syncBusy=false,lastSyncAt=0;
async function syncFromCloud({quiet=false}={}){if(!st.user||syncBusy)return;syncBusy=true;if(!quiet)setSyncState('syncing','Sincronizzo…');try{await loadCore();renderSports();renderCalendar();lastSyncAt=Date.now();setSyncState('ok','Sincronizzato')}catch(err){console.error(err);setSyncState('error','Sync non riuscita')}finally{syncBusy=false}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const msg=$('#loginMsg');msg.textContent='Accesso sicuro…';const email=$('#email').value.trim();const password=$('#password').value;let{error}=await db.auth.signInWithPassword({email,password});if(error){msg.textContent='Email o password non corrette.';return}msg.textContent=''};
$('#logoutBtn').onclick=()=>db.auth.signOut();
async function enter(user){st.user=user;$('#userMail').textContent=user.email||'';$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');await syncFromCloud()}
let{data:{session}}=await db.auth.getSession();if(session)await enter(session.user);
db.auth.onAuthStateChange((event,se)=>{if(se&&!st.user)setTimeout(()=>enter(se.user),0);if(!se){st.user=null;$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}});
addEventListener('online',()=>syncFromCloud());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastSyncAt>5000)syncFromCloud({quiet:true})});
setInterval(()=>{if(document.visibilityState==='visible')syncFromCloud({quiet:true})},45000);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
