
import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';import{SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY}from'./config.js';
const s=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),st={user:null,year:null,classes:[],sports:[],lessons:[],modules:[],exceptions:[],month:new Date(),exercises:[],replace:[],replaceId:null};
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),fmt=d=>new Intl.DateTimeFormat('it-IT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const phase={warmup:'ATTIVAZIONE',technical:'TECNICA',tactical:'PARTE CENTRALE',game:'PARTITA / SSG',assessment:'VALUTAZIONE',cooldown:'CHIUSURA',external:'ESPERTO ESTERNO',other:'ATTIVITÀ'};
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function view(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));let m={dashboard:['PANORAMICA','Dashboard'],calendar:['ANNO SCOLASTICO','Calendario'],classes:['GESTIONE','Classi'],planner:['MOTORE DIDATTICO','Programmazione'],archive:['800 SCHEDE','Archivio esercizi'],settings:['CONFIGURAZIONE','Impostazioni']}[v];$('#eyebrow').textContent=m[0];$('#title').textContent=m[1];if(v==='archive')archive();if(v==='calendar')calendar();if(v==='settings')settings()}
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>view(b.dataset.jump));$('#newModule').onclick=()=>view('planner');$$('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
async function core(){let[r1,r2,r3,r4,r5,r6]=await Promise.all([s.from('pe_school_years').select('*').eq('is_active',true).maybeSingle(),s.from('pe_classes').select('*').eq('archived',false).order('grade'),s.from('pe_sports').select('*').eq('active',true).order('name'),s.from('pe_lessons').select('*,pe_classes(name),pe_sports(name)').order('lesson_date').limit(150),s.from('pe_sport_modules').select('*,pe_classes(name),pe_sports(name)').order('start_date',{ascending:false}).limit(80),s.from('pe_calendar_exceptions').select('*').order('exception_date')]);st.year=r1.data;st.classes=r2.data||[];st.sports=r3.data||[];st.lessons=r4.data||[];st.modules=r5.data||[];st.exceptions=r6.data||[];selects()}
function selects(){let co='<option value="">Seleziona classe</option>'+st.classes.map(c=>`<option value="${c.id}">${esc(c.name)} · ${c.student_count} alunni</option>`).join(''),so='<option value="">Seleziona sport</option>'+st.sports.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#pClass').innerHTML=$('#eClass').innerHTML=co;$('#pSport').innerHTML=so;$('#sportFilter').innerHTML='<option value="">Tutti gli sport</option>'+st.sports.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(!$('#pStart').value)$('#pStart').value=new Date().toISOString().slice(0,10)}
function item(a,b,c=''){return`<div class="item"><div><b>${esc(a)}</b><small>${esc(b)}</small></div>${c}</div>`}
function dashboard(){$('#mClasses').textContent=st.classes.length;$('#mSports').textContent=st.sports.length;$('#mLessons').textContent=st.lessons.length;$('#mModules').textContent=st.modules.length;let today=new Date().toISOString().slice(0,10),u=st.lessons.filter(x=>x.lesson_date>=today).slice(0,6);$('#upcoming').innerHTML=u.map(x=>`<button class="item" data-lesson="${x.id}"><div><b>${esc(x.title)}</b><small>${esc(x.pe_classes?.name)} · ${fmt(x.lesson_date)}</small></div><span class="badge">${x.duration_min}'</span></button>`).join('')||item('Nessuna lezione','Ancora da pianificare');$('#recentModules').innerHTML=st.modules.slice(0,6).map(x=>item(x.title,`${x.pe_classes?.name||''} · ${x.planned_weeks} settimane`,`<span class="badge">${x.status}</span>`)).join('');$$('[data-lesson]').forEach(b=>b.onclick=()=>lesson(b.dataset.lesson))}
function classes(){$('#classGrid').innerHTML=st.classes.map(c=>`<div class="classBox"><small>CLASSE</small><h2>${esc(c.name)}</h2><p>${c.student_count} alunni</p><div class="chips"><span class="chip">Grado ${c.grade}</span>${c.general_level?`<span class="chip">Livello ${c.general_level}</span>`:''}</div></div>`).join('')}
function modules(){$('#moduleList').innerHTML=st.modules.map(x=>item(x.title,`${x.pe_classes?.name||''} · ${x.planned_weeks} settimane · ${x.lesson_duration_min}'`,`<span class="badge">${x.status}</span>`)).join('')||item('Nessun modulo','Generane uno dal pannello a sinistra')}
$('#moduleForm').onsubmit=async e=>{e.preventDefault();let cid=$('#pClass').value,sid=$('#pSport').value;if(!cid||!sid)return;let sport=st.sports.find(x=>x.id===sid),cl=st.classes.find(x=>x.id===cid);$('#plannerMsg').textContent='Genero la progressione…';let{data:m,error}=await s.from('pe_sport_modules').insert({owner_id:st.user.id,class_id:cid,sport_id:sid,module_type:'automatic',title:`${sport.name} · ${cl.name}`,start_date:$('#pStart').value,planned_weeks:+$('#pWeeks').value,lesson_duration_min:+$('#pDuration').value,level_override:$('#pLevel').value?+$('#pLevel').value:null,progression_mode:'progressive',status:'planned'}).select().single();if(error)return $('#plannerMsg').textContent=error.message;let{data,error:er}=await s.rpc('pe_generate_module_plan',{p_module_id:m.id,p_regenerate:false});if(er)return $('#plannerMsg').textContent=er.message;$('#plannerMsg').textContent='Programmazione generata con successo.';toast('Modulo generato');await core();dashboard();modules();calendar()}
async function lesson(id){let{data:l,error}=await s.from('pe_lessons').select('*,pe_classes(name),pe_sports(name)').eq('id',id).single();if(error)return toast(error.message);let{data:it}=await s.from('pe_lesson_exercises').select('*,pe_exercises(*)').eq('lesson_id',id).order('order_no');$('#lessonTitle').textContent=l.title;$('#lessonMeta').innerHTML=`<div class="chips"><span class="chip">${esc(l.pe_classes?.name)}</span><span class="chip">${fmt(l.lesson_date)}</span><span class="chip">${l.duration_min}'</span></div>`;$('#timeline').innerHTML=(it||[]).map(x=>`<div class="timelineItem"><div class="time">${x.duration_min}'</div><div><small>${phase[x.phase]||x.phase}</small><b>${esc(x.custom_title||x.pe_exercises?.name||'Attività')}</b><p>${esc(x.custom_explanation||x.pe_exercises?.student_explanation||'')}</p>${x.station_count?`<div class="chips"><span class="chip">${x.station_count} campi</span><span class="chip">${x.players_per_group} alunni/gruppo</span></div>`:''}</div><div class="actions">${x.exercise_id?`<button class="secondary" data-detail="${x.exercise_id}">Dettagli</button><button data-replace="${x.id}">Cambia</button>`:''}</div></div>`).join('');$$('[data-detail]').forEach(b=>b.onclick=()=>exercise(b.dataset.detail));$$('[data-replace]').forEach(b=>b.onclick=()=>replaceOpen(b.dataset.replace));$('#lessonModal').showModal()}
async function exercise(id){let{data:e,error}=await s.from('pe_exercises').select('*,pe_categories(name)').eq('id',id).single();if(error)return toast(error.message);$('#exerciseTitle').textContent=e.name;let box=(t,v)=>`<div><b>${t}</b><p>${esc(v||'—')}</p></div>`;$('#exerciseDetail').innerHTML=`<div class="chips"><span class="chip">${esc(e.pe_categories?.name||'')}</span><span class="chip">Liv. ${e.difficulty||'—'}</span><span class="chip">${e.duration_min||'—'}–${e.duration_max||'—'}'</span><span class="chip">${esc(e.field_dimensions||'')}</span></div><br><div class="detail">${box('COSA DEVI FARE',e.student_explanation)}${box('SPIEGAZIONE DOCENTE',e.teacher_explanation)}${box('OBIETTIVO',e.objective)}${box('ORGANIZZAZIONE',e.organization)}${box('REGOLE',e.rules)}${box('VARIANTI',e.variants)}${box('FACILITAZIONI',e.regressions)}${box('PROGRESSIONI',e.progressions)}${box('ERRORI',e.common_errors)}${box('CORREZIONI',e.corrections)}${box('CUE DOCENTE',e.teacher_cues)}${box('SICUREZZA',e.safety_notes)}</div>`;$('#exerciseModal').showModal()}
async function archive(){let q=s.from('pe_exercises').select('id,name,student_explanation,difficulty,duration_min,duration_max,fun_score,sport_id').eq('active',true).eq('audit_status','VERIFIED').order('name').limit(500);if($('#sportFilter').value)q=q.eq('sport_id',$('#sportFilter').value);if($('#diffFilter').value)q=q.eq('difficulty',+$('#diffFilter').value);if($('#search').value.trim())q=q.ilike('name',`%${$('#search').value.trim()}%`);let{data,error}=await q;if(error)return toast(error.message);st.exercises=data||[];$('#exerciseGrid').innerHTML=st.exercises.map(e=>`<div class="exercise"><h4>${esc(e.name)}</h4><p>${esc(e.student_explanation?.slice(0,150)||'')}</p><div class="chips"><span class="chip">Liv. ${e.difficulty||'—'}</span><span class="chip">${e.duration_min||'—'}–${e.duration_max||'—'}'</span>${e.fun_score?`<span class="chip">Fun ${e.fun_score}/5</span>`:''}</div><br><button class="secondary" data-detail="${e.id}">Apri scheda</button></div>`).join('');$$('[data-detail]').forEach(b=>b.onclick=()=>exercise(b.dataset.detail))}
['search','sportFilter','diffFilter'].forEach(id=>document.getElementById(id).addEventListener(id==='search'?'input':'change',archive));
async function replaceOpen(id){st.replaceId=id;let{data,error}=await s.rpc('pe_replacement_candidates',{p_lesson_exercise_id:id});if(error)return toast(error.message);st.replace=Array.isArray(data)?data:(data?.items||[]);replaceRender();$('#replaceModal').showModal()}
function replaceRender(){let term=$('#replaceSearch').value.toLowerCase(),d=$('#replaceDiff').value,x=st.replace.filter(e=>(!term||e.name?.toLowerCase().includes(term))&&(!d||String(e.difficulty)===d));$('#replaceGrid').innerHTML=x.map(e=>`<div class="exercise"><h4>${esc(e.name)}</h4><p>${esc(e.student_explanation?.slice(0,120)||e.objective||'')}</p><div class="chips"><span class="chip">Liv. ${e.difficulty||'—'}</span><span class="chip">${e.duration_min||'—'}–${e.duration_max||'—'}'</span></div><br><button data-use="${e.id}">Usa questo</button></div>`).join('');$$('[data-use]').forEach(b=>b.onclick=()=>useExercise(b.dataset.use))}
$('#replaceSearch').oninput=replaceRender;$('#replaceDiff').onchange=replaceRender;
async function useExercise(id){let{error}=await s.rpc('pe_replace_lesson_exercise',{p_lesson_exercise_id:st.replaceId,p_new_exercise_id:id,p_reason:'Sostituzione manuale da PE Teacher OS'});if(error)return toast(error.message);$('#replaceModal').close();toast('Esercizio sostituito');let{data:x}=await s.from('pe_lesson_exercises').select('lesson_id').eq('id',st.replaceId).single();if(x){$('#lessonModal').close();lesson(x.lesson_id)}}
function calendar(){let d=st.month,y=d.getFullYear(),m=d.getMonth();$('#calTitle').textContent=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}).format(d);let first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7)),heads=['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(x=>`<div class="calHead">${x}</div>`).join(''),html=heads;for(let i=0;i<42;i++){let x=new Date(start);x.setDate(start.getDate()+i);let iso=x.toISOString().slice(0,10),ev=st.lessons.filter(z=>z.lesson_date===iso).map(z=>`<div class="event" data-lesson="${z.id}">${esc(z.title)}</div>`).join(''),ex=st.exceptions.filter(z=>iso>=z.exception_date&&iso<=(z.end_date||z.exception_date)).map(z=>`<div class="event exception">${esc(z.reason||z.exception_type)}</div>`).join('');html+=`<div class="day ${x.getMonth()!==m?'off':''}"><div class="num">${x.getDate()}</div>${ex}${ev}</div>`}$('#calGrid').innerHTML=html;$$('#calGrid [data-lesson]').forEach(b=>b.onclick=()=>lesson(b.dataset.lesson))}
$('#prev').onclick=()=>{st.month=new Date(st.month.getFullYear(),st.month.getMonth()-1,1);calendar()};$('#next').onclick=()=>{st.month=new Date(st.month.getFullYear(),st.month.getMonth()+1,1);calendar()};
function openException(scope){$('#eScope').value=scope;$('#eClassWrap').classList.toggle('hidden',scope==='school');$('#exceptionModal').showModal()}$('#addException').onclick=()=>openException('school');$('#schoolClose').onclick=()=>openException('school');$('#eScope').onchange=()=>$('#eClassWrap').classList.toggle('hidden',$('#eScope').value==='school');
$('#exceptionForm').onsubmit=async e=>{e.preventDefault();let school=$('#eScope').value==='school',p={owner_id:st.user.id,school_year_id:st.year?.id||null,class_id:school?null:$('#eClass').value,exception_date:$('#eStart').value,end_date:$('#eEnd').value,scope:school?'school':'class',exception_type:$('#eType').value,reason:$('#eReason').value||null,all_day:true};let{error}=await s.from('pe_calendar_exceptions').insert(p);if(error)return toast(error.message);$('#exceptionModal').close();await core();calendar();settings();toast('Calendario aggiornato')}
async function settings(){let school=st.exceptions.filter(x=>x.scope==='school');$('#closures').innerHTML=school.map(x=>item(x.reason||'Chiusura',`${fmt(x.exception_date)}${x.end_date!==x.exception_date?' → '+fmt(x.end_date):''}`,`<span class="badge">${x.exception_type}</span>`)).join('')||item('Nessuna chiusura','Inserisci vacanze e ponti');let{data}=await s.from('pe_class_timetable_slots').select('*,pe_classes(name)').eq('active',true).order('weekday'),days=['','Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];$('#timetable').innerHTML=(data||[]).map(x=>item(x.pe_classes?.name||'',`${days[x.weekday]} · ${x.start_time?.slice(0,5)}–${x.end_time?.slice(0,5)}`,`<span class="badge">${x.lesson_minutes}'</span>`)).join('')||item('Orario non impostato','Lo inserirai a settembre')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#msg').textContent='Accesso…';let{error}=await s.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});$('#msg').textContent=error?error.message:''};$('#logout').onclick=()=>s.auth.signOut();
async function enter(u){st.user=u;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await core();dashboard();classes();modules();calendar();settings()}
let{data:{session}}=await s.auth.getSession();if(session)enter(session.user);s.auth.onAuthStateChange((_,se)=>{if(se&&!st.user)enter(se.user);if(!se){st.user=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
